version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tabadulat_123
      POSTGRES_DB: notes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:tabadulat_123@notes:5432/notes
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
